"""
config_builder.py  —  Generates Config.py from the UI payload (buildCfg in app.js).
"""


def build_config_py(cfg: dict) -> str:

    def b(val):
        if isinstance(val, bool):
            return "True" if val else "False"
        if isinstance(val, str):
            return "True" if val.lower() in ("true", "1", "yes", "on") else "False"
        return "True" if val else "False"

    def s(val):
        if val is None or val == "":
            return "None"
        return '"{}"'.format(val)

    def p(val):
        """Path helper — converts backslashes to forward slashes (safe on Windows)."""
        if val is None or val == "":
            val = "C:/Users/HP/Documents/input/main_qexcel.xlsx"
        val = val.replace("\\", "/")
        return '"{}"'.format(val)

    def g(key, default=None):
        return cfg.get(key, default)

    def pylist(val, default):
        """Convert a value (list or newline-separated string) to a Python list literal."""
        if val is None:
            return repr(default)
        if isinstance(val, list):
            items = [x for x in val if x]
            return repr(items) if items else repr(default)
        # Newline-separated string from a textarea
        items = [x.strip() for x in str(val).split("\n") if x.strip()]
        return repr(items) if items else repr(default)

    # ------------------------------------------------------------------
    # Login
    # ------------------------------------------------------------------
    use_login = g("USE_CUSTOM_LOGIN", False)
    if isinstance(use_login, str):
        use_login = use_login.lower() in ("true", "1", "yes", "on")

    email_val    = s(g("email"))    if use_login else "None"
    password_val = s(g("password")) if use_login else "None"

    # ------------------------------------------------------------------
    # Resolve merged fields (Ad-hoc vs Audit Plan)
    # ------------------------------------------------------------------
    group_name_val = g("Group_Name_adhoc")    or g("Group_Name")    or ""
    auditor1_val   = g("Auditor1_adhoc") or g("oa_Auditor1") or g("Auditor1") or ""
    auditor2_val   = g("Auditor2_adhoc") or g("oa_Auditor2") or g("Auditor2") or ""
    ap_audit_name_val = g("ap_audit_name") or "Ongoing Audit"

    # ------------------------------------------------------------------
    # Derive top-level group flags from their sub-module flags
    # ------------------------------------------------------------------
    _run_Q_audit   = any([
        bool(g("run_q_setting")),
        bool(g("run_Q_SA")),
        bool(g("run_Q_SA1")),
        bool(g("run_Q_as_table")),
        bool(g("run_Q_Recently_Audit")),
        bool(g("run_Q_audit_Summary")),
    ])
    # Use the UI group-level toggle directly; fall back to sub-flag derivation
    _run_Audit_plan = (
        bool(g("run_Audit_plan", False))
        or bool(g("run_create_audit", False))
        or bool(g("run_create_Ad_hoc_Audit", False))
        or bool(g("run_timezone", False))
        or bool(g("run_setup_Audit", False))
        or bool(g("run_A_SA", False))
        or bool(g("run_A_SA2", False))
        or bool(g("run_A_as_table", False))
        or bool(g("run_A_audit_Summary", False))
        or bool(g("run_A_Recently_Audit", False))
    )
    _run_inventory = any([
        bool(g("run_create_group", False)),
        bool(g("run_locatio_setup", False)),   # keep the legacy typo key consistent
        bool(g("run_import_app", False)),
    ])

    content = '''# Auto-generated by Q-Audit Runner
import os


class Config:

    DEFAULT_TIMEOUT   = {DEFAULT_TIMEOUT}
    SHORT_TIMEOUT     = {SHORT_TIMEOUT}
    WAIT_AFTER_ACTION = {WAIT_AFTER_ACTION}

    USE_CUSTOM_LOGIN = {USE_CUSTOM_LOGIN}

    # Login credentials (only active when USE_CUSTOM_LOGIN = True)
    email    = {email}
    password = {password}

    browsername  = {browsername}
    environments = {environments}

    Branch     = {Branch}
    audit_name = {audit_name}

    Auditor_name1 = {Auditor_name1}
    Auditor_name2 = {Auditor_name2}
    Auditor_name3 = {Auditor_name3}

    Checkboxes_Audit_Damaged = {Checkboxes_Audit_Damaged}
    Checkboxes_StockItems    = {Checkboxes_StockItems}
    Checkboxes_geo           = {Checkboxes_geo}
    Checkboxes_photo         = {Checkboxes_photo}

    A_Type = {A_Type}
    mapping = {mapping}

    # --- Group flags (derived from sub-module flags) ---
    run_Q_audit    = {run_Q_audit}
    run_Audit_plan = {run_Audit_plan}
    run_inventory  = {run_inventory}

    # Module run flags — Q Audit
    run_q_setting        = {run_q_setting}
    run_Q_SA             = {run_Q_SA}
    run_Q_SA1            = {run_Q_SA1}
    run_Q_as_table       = {run_Q_as_table}
    run_Q_Recently_Audit = {run_Q_Recently_Audit}
    run_Q_audit_Summary  = {run_Q_audit_Summary}

    # Module run flags — Audit Creation
    run_create_audit        = {run_create_audit}
    run_create_Ad_hoc_Audit = {run_create_Ad_hoc_Audit}
    run_setup_Audit         = {run_setup_Audit}
    run_A_SA                = {run_A_SA}
    run_timezone            = {run_timezone}

    # Module run flags — Auditor 2
    run_new_add_item2    = {run_new_add_item2}
    run_A_SA2            = {run_A_SA2}
    run_A_SA_table       = {run_A_SA_table}
    run_A_as_table       = {run_A_SA_table}  # legacy key for app.py
    run_A_audit_Summary  = {run_A_audit_Summary}
    run_A_Recently_Audit = {run_A_Recently_Audit}

    MODULE_RUN_ORDER = {MODULE_RUN_ORDER}

    # Inventory
    run_create_group  = {run_create_group}
    run_locatio_setup = {run_locatio_setup}
    run_import_app    = {run_import_app}

    EXCEL_PATH = {EXCEL_PATH}

    # ---------------------------
    # Q Audit - Setting
    # ---------------------------
    AUDITOR_MAPPING_TYPE        = {AUDITOR_MAPPING_TYPE}
    EXCEL_SHEET_AUDITOR_MAPPING = {EXCEL_SHEET_AUDITOR_MAPPING}
    EXCEL_auditor_col           = {EXCEL_auditor_col}
    EXCEL_category_col          = {EXCEL_category_col}
    EXCEL_storage_col           = {EXCEL_storage_col}

    # ---------------------------
    # Q_SA module — run Auditor 1 stock audit
    # ---------------------------
    location1 = {location1}
    code1     = {code1}
    aud_qty1  = {aud_qty1}
    dam_qty1  = {dam_qty1}

    # ---------------------------
    # Q_SA1 — run Auditor 2 stock audit
    # ---------------------------
    location2 = {location2}
    code2     = {code2}
    aud_qty2  = {aud_qty2}
    dam_qty2  = {dam_qty2}

    # ---------------------------
    # Q Audit - Summary Report
    # ---------------------------
    EXCEL_SHEET_audit_Summary   = {EXCEL_SHEET_audit_Summary}
    FILTER_COLUMN               = {FILTER_COLUMN}

    # ---------------------------
    # Auditor 1 - Item Add
    # ---------------------------
    ITEM_CODE1    = {ITEM_CODE1}
    ITEM_NAME1    = {ITEM_NAME1}
    CATEGORY1     = {CATEGORY1}
    COST_PRICE1   = {COST_PRICE1}
    SELL_PRICE1   = {SELL_PRICE1}
    LOCATION1     = {LOCATION1}
    BARCODE1      = {BARCODE1}
    UOM1          = {UOM1}
    audited_qty1  = {audited_qty1}
    damaged_qty1  = {damaged_qty1}
    run_new_add_item = {run_new_add_item}

    # ---------------------------
    # Auditor 1 - Count Upload
    # ---------------------------
    EXCEL_SHEET_auditor_1 = {EXCEL_SHEET_auditor_1}
    EXCEL_LOCATION_COL1   = {EXCEL_LOCATION_COL1}
    EXCEL_CODE_COL1       = {EXCEL_CODE_COL1}
    EXCEL_AUDITED_COL1    = {EXCEL_AUDITED_COL1}
    EXCEL_DAMAGED_COL1    = {EXCEL_DAMAGED_COL1}

    # ---------------------------
    # Auditor 2 - Item Add
    # ---------------------------
    ITEM_CODE2    = {ITEM_CODE2}
    ITEM_NAME2    = {ITEM_NAME2}
    CATEGORY2     = {CATEGORY2}
    COST_PRICE2   = {COST_PRICE2}
    SELL_PRICE2   = {SELL_PRICE2}
    LOCATION2     = {LOCATION2}
    BARCODE2      = {BARCODE2}
    UOM2          = {UOM2}
    audited_qty2  = {audited_qty2}
    damaged_qty2  = {damaged_qty2}

    # ---------------------------
    # Auditor 2 - Count Upload
    # ---------------------------
    EXCEL_SHEET_auditor_2 = {EXCEL_SHEET_auditor_2}
    EXCEL_LOCATION_COL2   = {EXCEL_LOCATION_COL2}
    EXCEL_CODE_COL2       = {EXCEL_CODE_COL2}
    EXCEL_AUDITED_COL2    = {EXCEL_AUDITED_COL2}
    EXCEL_DAMAGED_COL2    = {EXCEL_DAMAGED_COL2}
    
    # ---------------------------
    # Shared / Combined Credentials
    # ---------------------------
    email2    = {email2}
    password2 = {password2}

    # ---------------------------
    # Reports / Summary Sheet Names
    # ---------------------------
    EXCEL_SHEET_as_table       = {EXCEL_SHEET_as_table}
    EXCEL_SHEET_audit_Summary  = {EXCEL_SHEET_audit_Summary}
    EXCEL_SHEET_Recently_Audit = {EXCEL_SHEET_Recently_Audit}

    # ---------------------------
    # Audit Plan Setup
    # ---------------------------
    Audit_Owner   = {Audit_Owner}
    Auditor1      = {Auditor1}
    Auditor2      = {Auditor2}
    Group_Name    = {Group_Name}
    ap_audit_name = {ap_audit_name}
    Audit_Type    = {Audit_Type}
    frequency     = {frequency}
    Day_s         = {Day_s}
    Target__Day   = {Target__Day}
    Target_Date   = {Target_Date}

    A_Checkboxes_Audit_Damaged = {A_Checkboxes_Audit_Damaged}
    A_Checkboxes_StockItems    = {A_Checkboxes_StockItems}
    A_Checkboxes_geo           = {A_Checkboxes_geo}
    A_Checkboxes_photo         = {A_Checkboxes_photo}

    CROSS_AUDIT_TYPE   = {CROSS_AUDIT_TYPE}
    CROSS_Auditor_name = {CROSS_Auditor_name}
    AUDIT_MAPPING_TYPE = {AUDIT_MAPPING_TYPE}

    # ---------------------------
    # Ongoing Audit
    # ---------------------------
    oa_group_name    = {oa_group_name}
    oa_email         = {oa_email}
    oa_password      = {oa_password}
    oa_excel_path    = {oa_excel_path}
    oa_sheet         = {oa_sheet}

    oa_Auditor1      = {oa_Auditor1}
    oa_Auditor2      = {oa_Auditor2}

    oa_A_Checkboxes_Audit_Damaged = {oa_A_Checkboxes_Audit_Damaged}
    oa_A_Checkboxes_StockItems    = {oa_A_Checkboxes_StockItems}
    oa_A_Checkboxes_geo           = {oa_A_Checkboxes_geo}
    oa_A_Checkboxes_photo         = {oa_A_Checkboxes_photo}

    oa_mapping = {oa_mapping}

    # --- Inventory Setup ---
    group_name     = {group_name}
    inventory_type = {inventory_type}
    fields         = {fields}
    ids            = {ids}

    # ---------------------------
    # Import Items
    # ---------------------------
    EXCEL_FILE          = {EXCEL_FILE}
    run_add_item        = {run_add_item}
    run_quick_add_items = {run_quick_add_items}
    run_import_items    = {run_import_items}
    sheet_name          = {sheet_name}
    Item_Name           = {Item_Name}
    Item_Code           = {Item_Code}
    Item_UOM            = {Item_UOM}
    Item_Category       = {Item_Category}
    Item_Tag            = {Item_Tag}
    Item_CP             = {Item_CP}
    Item_SP             = {Item_SP}
    Item_Barcode        = {Item_Barcode}
'''.format(
        DEFAULT_TIMEOUT   = g("DEFAULT_TIMEOUT",   10000),
        SHORT_TIMEOUT     = g("SHORT_TIMEOUT",     5000),
        WAIT_AFTER_ACTION = g("WAIT_AFTER_ACTION", 300),
        USE_CUSTOM_LOGIN  = b(g("USE_CUSTOM_LOGIN", False)),
        email             = email_val,
        password          = password_val,
        browsername       = s(g("browsername",  "chrome")),
        environments      = s(g("environments", "PRODUCTION")),
        Branch            = s(g("Branch",       "nm")),
        audit_name        = s(g("audit_name",   "")),
        Auditor_name1     = s(g("Auditor_name1")),
        Auditor_name2     = s(g("Auditor_name2")),
        Auditor_name3     = s(g("Auditor_name3")),
        Checkboxes_Audit_Damaged = b(g("Checkboxes_Audit_Damaged", False)),
        Checkboxes_StockItems    = b(g("Checkboxes_StockItems",    False)),
        Checkboxes_geo           = b(g("Checkboxes_geo",           False)),
        Checkboxes_photo         = b(g("Checkboxes_photo",         False)),
        A_Type                   = s(g("A_Type", "Audit_plan")),
        mapping                  = repr(g("mapping", {})),
        # Group flags
        run_Q_audit    = b(_run_Q_audit),
        run_Audit_plan = b(_run_Audit_plan),
        run_inventory  = b(_run_inventory),
        # Module flags
        run_q_setting        = b(g("run_q_setting",        False)),
        run_Q_SA             = b(g("run_Q_SA",             False)),
        run_Q_SA1            = b(g("run_Q_SA1",            False)),
        run_Q_as_table       = b(g("run_Q_as_table",       False)),
        run_Q_Recently_Audit = b(g("run_Q_Recently_Audit", False)),
        run_Q_audit_Summary  = b(g("run_Q_audit_Summary",  False)),
        # Audit Creation
        run_create_audit        = b(g("run_create_audit",        False)),
        run_create_Ad_hoc_Audit = b(g("run_create_Ad_hoc_Audit", False)),
        run_setup_Audit         = b(g("run_setup_Audit",         False)),
        run_A_SA                = b(g("run_A_SA",                False)),
        run_timezone            = b(g("run_timezone",            False)),
        # Auditor 2
        run_new_add_item2    = b(g("run_new_add_item2",    False)),
        run_A_SA2            = b(g("run_A_SA2",            False)),
        run_A_SA_table       = b(g("run_A_as_table",       g("run_A_SA_table", False))),
        run_A_audit_Summary  = b(g("run_A_audit_Summary",  False)),
        run_A_Recently_Audit = b(g("run_A_Recently_Audit", False)),
        MODULE_RUN_ORDER     = repr(g("MODULE_RUN_ORDER", [])),
        # Inventory
        run_create_group  = b(g("run_create_group",  False)),
        run_locatio_setup = b(g("run_locatio_setup", False)),
        EXCEL_PATH                   = p(g("EXCEL_PATH")),
        AUDITOR_MAPPING_TYPE         = s(g("AUDITOR_MAPPING_TYPE",        "Random")),
        EXCEL_SHEET_AUDITOR_MAPPING  = s(g("EXCEL_SHEET_AUDITOR_MAPPING")),
        EXCEL_auditor_col            = s(g("EXCEL_auditor_col",           "Auditor")),
        EXCEL_category_col           = s(g("EXCEL_category_col",          "Category")),
        EXCEL_storage_col            = s(g("EXCEL_storage_col",           "Storage")),
        location1    = s(g("location1", "SA-A1")),
        code1        = s(g("code1",     "ABC1123")),
        aud_qty1     = g("aud_qty1", 0),
        dam_qty1     = g("dam_qty1", 0),
        location2    = s(g("location2", "SA-A1")),
        code2        = s(g("code2",     "ABC1123")),
        aud_qty2     = g("aud_qty2", 0),
        dam_qty2     = g("dam_qty2", 0),
        EXCEL_SHEET_audit_Summary    = s(g("EXCEL_SHEET_audit_Summary", "auditSummary")),
        FILTER_COLUMN                = s(g("FILTER_COLUMN", "filter")),
        ITEM_CODE1    = s(g("ITEM_CODE1", "ABC1123")),
        ITEM_NAME1    = s(g("ITEM_NAME1", "Test Item")),
        CATEGORY1     = s(g("CATEGORY1", "Gear")),
        COST_PRICE1   = s(g("COST_PRICE1", "100")),
        SELL_PRICE1   = s(g("SELL_PRICE1", "100")),
        LOCATION1     = s(g("LOCATION1", "SA-A1")),
        BARCODE1      = s(g("BARCODE1", "123456789")),
        UOM1          = s(g("UOM1", "PCS")),
        audited_qty1  = g("audited_qty1", 10),
        damaged_qty1  = g("damaged_qty1", 0),
        run_new_add_item      = b(g("run_new_add_item", False)),
        EXCEL_SHEET_auditor_1 = s(g("EXCEL_SHEET_auditor_1", "auditor_1")),
        EXCEL_LOCATION_COL1   = s(g("EXCEL_LOCATION_COL1",   "locations")),
        EXCEL_CODE_COL1       = s(g("EXCEL_CODE_COL1",       "code")),
        EXCEL_AUDITED_COL1    = s(g("EXCEL_AUDITED_COL1",    "audited")),
        EXCEL_DAMAGED_COL1    = s(g("EXCEL_DAMAGED_COL1",    "damaged")),
        ITEM_CODE2    = s(g("ITEM_CODE2", "ABC1123")),
        ITEM_NAME2    = s(g("ITEM_NAME2", "Test Item")),
        CATEGORY2     = s(g("CATEGORY2", "Gear")),
        COST_PRICE2   = s(g("COST_PRICE2", "100")),
        SELL_PRICE2   = s(g("SELL_PRICE2", "100")),
        LOCATION2     = s(g("LOCATION2", "SA-A1")),
        BARCODE2      = s(g("BARCODE2", "123456789")),
        UOM2          = s(g("UOM2", "PCS")),
        audited_qty2  = g("audited_qty2", 10),
        damaged_qty2  = g("damaged_qty2", 0),
        EXCEL_SHEET_auditor_2 = s(g("EXCEL_SHEET_auditor_2", "auditor_2")),
        EXCEL_LOCATION_COL2   = s(g("EXCEL_LOCATION_COL2",   "locations")),
        EXCEL_CODE_COL2       = s(g("EXCEL_CODE_COL2",       "code")),
        EXCEL_AUDITED_COL2    = s(g("EXCEL_AUDITED_COL2",    "audited")),
        EXCEL_DAMAGED_COL2    = s(g("EXCEL_DAMAGED_COL2",    "damaged")),
        email2                = s(g("email2")),
        password2             = s(g("password2")),
        EXCEL_SHEET_as_table       = s(g("EXCEL_SHEET_as_table",       "as_table")),
        EXCEL_SHEET_Recently_Audit = s(g("EXCEL_SHEET_Recently_Audit", "Recently_Audit")),
        Audit_Owner   = s(g("Audit_Owner",  "Dinesh B")),
        Auditor1      = s(g("Auditor1", "")),
        Auditor2      = s(g("Auditor2", "")),
        Group_Name    = s(g("Group_Name", "")),
        ap_audit_name = s(g("ap_audit_name", "")),
        Audit_Type    = s(g("Audit_Type",   "Complete Count")),
        frequency     = s(g("frequency",    "one-time")),
        Day_s         = g("Day_s", 30),
        Target__Day   = s(g("Target__Day",  "Thursday")),
        Target_Date   = s(g("Target_Date",  "05/03/2026")),
        A_Checkboxes_Audit_Damaged = b(g("A_Checkboxes_Audit_Damaged", False)),
        A_Checkboxes_StockItems    = b(g("A_Checkboxes_StockItems",    False)),
        A_Checkboxes_geo           = b(g("A_Checkboxes_geo",           False)),
        A_Checkboxes_photo         = b(g("A_Checkboxes_photo",         False)),
        CROSS_AUDIT_TYPE   = s(g("CROSS_AUDIT_TYPE",   "Random Recheck")),
        CROSS_Auditor_name = s(g("CROSS_Auditor_name", "Dinesh")),
        AUDIT_MAPPING_TYPE = s(g("AUDIT_MAPPING_TYPE", "Random")),
        group_name     = s(g("inv_group_name",  "Group_34")),
        inventory_type = s(g("inventory_type",  "Serialized")),
        fields         = pylist(g("inv_fields"),  ["Item Code", "Item Name"]),
        ids            = pylist(g("inv_ids"),     ["Id1Name", "Id2Name", "Id3Name"]),
        run_import_app        = b(g("run_import_app", False)),
        EXCEL_FILE            = p(g("EXCEL_FILE")),
        run_add_item          = b(g("run_add_item", False)),
        run_quick_add_items   = b(g("run_quick_add_items", False)),
        run_import_items      = b(g("run_import_items", False)),
        sheet_name            = s(g("sheet_name", "Data")),
        Item_Name             = s(g("Item_Name", "ab,cm12")),
        Item_Code             = s(g("Item_Code", "itme173")),
        Item_UOM              = s(g("Item_UOM", "km")),
        Item_Category         = s(g("Item_Category", "Category132!")),
        Item_Tag              = s(g("Item_Tag", "test tag1")),
        Item_CP               = g("Item_CP", 100),
        Item_SP               = g("Item_SP", 150),
        Item_Barcode          = s(g("Item_Barcode", "1234u56789")),
        # Ongoing Audit
        oa_group_name    = s(g("oa_group_name", "")),
        oa_email         = s(g("oa_email")),
        oa_password      = s(g("oa_password")),
        oa_excel_path    = p(g("oa_excel_path", "")),
        oa_sheet         = s(g("oa_sheet", "Data")),
        oa_Auditor1      = s(g("oa_Auditor1", "")),
        oa_Auditor2      = s(g("oa_Auditor2", "")),
        oa_A_Checkboxes_Audit_Damaged = b(g("oa_A_Checkboxes_Audit_Damaged", False)),
        oa_A_Checkboxes_StockItems    = b(g("oa_A_Checkboxes_StockItems",    False)),
        oa_A_Checkboxes_geo           = b(g("oa_A_Checkboxes_geo",           False)),
        oa_A_Checkboxes_photo         = b(g("oa_A_Checkboxes_photo",         False)),
        oa_mapping                    = repr(g("oa_mapping", {})),
    )
    return content
