# Auto-generated by Q-Audit Runner
import os


class Config:

    DEFAULT_TIMEOUT   = 10000
    SHORT_TIMEOUT     = 5000
    WAIT_AFTER_ACTION = 300

    USE_CUSTOM_LOGIN = False

    # Login credentials (only active when USE_CUSTOM_LOGIN = True)
    email    = None
    password = None

    browsername  = "chrome"
    environments = "PRODUCTION"

    Branch     = "nm"
    audit_name = "Audit_TEST_14"

    Auditor_name1 = "dine"
    Auditor_name2 = "egggg tttt"
    Auditor_name3 = None

    Checkboxes_Audit_Damaged = False
    Checkboxes_StockItems    = False
    Checkboxes_geo           = False
    Checkboxes_photo         = False

    A_Type = "Audit_plan"
    mapping = {}

    # --- Group flags (derived from sub-module flags) ---
    run_Q_audit    = False
    run_Audit_plan = True
    run_inventory  = False

    # Module run flags — Q Audit
    run_q_setting        = False
    run_Q_SA             = False
    run_Q_SA1            = False
    run_Q_as_table       = False
    run_Q_Recently_Audit = False
    run_Q_audit_Summary  = False

    # Module run flags — Audit Creation
    run_create_audit        = True
    run_create_Ad_hoc_Audit = False
    run_setup_Audit         = False
    run_A_SA                = True
    run_timezone            = True

    # Module run flags — Auditor 2
    run_new_add_item2    = True
    run_A_SA2            = True
    run_A_SA_table       = False
    run_A_as_table       = False  # legacy key for app.py
    run_A_audit_Summary  = False
    run_A_Recently_Audit = False

    MODULE_RUN_ORDER = ['run_A_SA', 'run_A_SA2']

    # Inventory
    run_create_group  = False
    run_locatio_setup = False
    run_import_app    = False

    EXCEL_PATH = "g:/My Drive/vs code/test/.vscode/main/qa_runner/uploads/main_qexcel (10).xlsx"

    # ---------------------------
    # Q Audit - Setting
    # ---------------------------
    AUDITOR_MAPPING_TYPE        = "Random"
    EXCEL_SHEET_AUDITOR_MAPPING = None
    EXCEL_auditor_col           = "Auditor"
    EXCEL_category_col          = "Category"
    EXCEL_storage_col           = "Storage"

    # ---------------------------
    # Q_SA module — run Auditor 1 stock audit
    # ---------------------------
    location1 = "SA-A2-B3-L3"
    code1     = "ABC1123"
    aud_qty1  = 10
    dam_qty1  = 0

    # ---------------------------
    # Q_SA1 — run Auditor 2 stock audit
    # ---------------------------
    location2 = "SA-A2-B3-L3"
    code2     = "ABC11234"
    aud_qty2  = 10
    dam_qty2  = 0

    # ---------------------------
    # Q Audit - Summary Report
    # ---------------------------
    EXCEL_SHEET_audit_Summary   = "auditSummary"
    FILTER_COLUMN               = "filter"

    # ---------------------------
    # Auditor 1 - Item Add
    # ---------------------------
    ITEM_CODE1    = "ABC1123"
    ITEM_NAME1    = "Test Item"
    CATEGORY1     = "Gear"
    COST_PRICE1   = "100"
    SELL_PRICE1   = "100"
    LOCATION1     = "SA-A1"
    BARCODE1      = "123456789"
    UOM1          = "PCS"
    audited_qty1  = 10
    damaged_qty1  = 0
    run_new_add_item = False

    # ---------------------------
    # Auditor 1 - Count Upload
    # ---------------------------
    EXCEL_SHEET_auditor_1 = "auditor_1"
    EXCEL_LOCATION_COL1   = "locations"
    EXCEL_CODE_COL1       = "code"
    EXCEL_AUDITED_COL1    = "audited"
    EXCEL_DAMAGED_COL1    = "damaged"

    # ---------------------------
    # Auditor 2 - Item Add
    # ---------------------------
    ITEM_CODE2    = "ABC1123"
    ITEM_NAME2    = "Test Item"
    CATEGORY2     = "Gear"
    COST_PRICE2   = "100"
    SELL_PRICE2   = "100"
    LOCATION2     = "SA-A1"
    BARCODE2      = "123456789"
    UOM2          = "PCS"
    audited_qty2  = 10
    damaged_qty2  = 0

    # ---------------------------
    # Auditor 2 - Count Upload
    # ---------------------------
    EXCEL_SHEET_auditor_2 = "auditor_2"
    EXCEL_LOCATION_COL2   = "locations"
    EXCEL_CODE_COL2       = "code"
    EXCEL_AUDITED_COL2    = "audited"
    EXCEL_DAMAGED_COL2    = "damaged"
    
    # ---------------------------
    # Shared / Combined Credentials
    # ---------------------------
    email2    = "yoiffoweuroipre-7178@yopmail.com"
    password2 = "MeNx6G2S"

    # ---------------------------
    # Reports / Summary Sheet Names
    # ---------------------------
    EXCEL_SHEET_as_table       = "as_table"
    EXCEL_SHEET_audit_Summary  = "auditSummary"
    EXCEL_SHEET_Recently_Audit = "Recently_Audit"

    # ---------------------------
    # Audit Plan Setup
    # ---------------------------
    Audit_Owner   = "Dinesh B"
    Auditor1      = "fff dd"
    Auditor2      = "wwork w B"
    Group_Name    = "Test Group Automation 38110"
    ap_audit_name = "Audit_TEST_14i"
    Audit_Type    = "Complete Count"
    frequency     = "one-time"
    Day_s         = 30
    Target__Day   = "Thursday"
    Target_Date   = "05/03/2026"

    A_Checkboxes_Audit_Damaged = False
    A_Checkboxes_StockItems    = False
    A_Checkboxes_geo           = False
    A_Checkboxes_photo         = False

    CROSS_AUDIT_TYPE   = "Random Recheck"
    CROSS_Auditor_name = "Dinesh"
    AUDIT_MAPPING_TYPE = "Random"

    # ---------------------------
    # Ongoing Audit
    # ---------------------------
    oa_group_name    = "Group_341"
    oa_email         = None
    oa_password      = None
    oa_excel_path    = "g:/My Drive/vs code/test/.vscode/main/qa_runner/uploads/main_qexcel (10).xlsx"
    oa_sheet         = "auditor_1"

    oa_Auditor1      = "dine"
    oa_Auditor2      = "egggg tttt"

    oa_A_Checkboxes_Audit_Damaged = False
    oa_A_Checkboxes_StockItems    = False
    oa_A_Checkboxes_geo           = False
    oa_A_Checkboxes_photo         = False

    oa_mapping = {}

    # --- Inventory Setup ---
    group_name     = "Group_34"
    inventory_type = "Serialized"
    fields         = ['Item Code', 'Item Name']
    ids            = ['Serial Number', 'IMEI', 'Barcode']

    # ---------------------------
    # Import Items
    # ---------------------------
    EXCEL_FILE          = "C:/Users/HP/Documents/input/main_qexcel.xlsx"
    run_add_item        = False
    run_quick_add_items = False
    run_import_items    = False
    sheet_name          = "Data"
    Item_Name           = "ab,cm12"
    Item_Code           = "itme173"
    Item_UOM            = "km"
    Item_Category       = "Category132!"
    Item_Tag            = "test tag1"
    Item_CP             = 100
    Item_SP             = 150
    Item_Barcode        = "1234u56789"
